[model]
link = "https://en.wikipedia.org/wiki/S%26P_100#Components"
rf = 0.05
div = 0.04


[view]
title = "Black-Scholes-Merton pricer"
logo = "logo.ico"
major_title = "BSM model on random Portfolio"
minor_title = "BSM Model on selected option"
foreground_1 = "green"
foreground_2 = "red"


[controller]
error_type = "Please enter Option type"
error_mat = "The maturity should be in DD/MM/YYYY"
error_msg = "Attribute missing, please check your input"
error_ticker = "You are using an incorrect  TICKER, please check"

[chart]
sheet_name = "Portfolio"
file = "BSM_portfolio.xlsx"
style = "seaborn-v0_8-darkgrid"
pdf = "Options_graph.pdf"
call_color = "green"
put_color = "blue"
